### ISSUE TITLE
Documentation: add explanation for new pokey pokey hole technique.

### ISSUE THREAD

**Issue by miklschmidt** [EVA-3D/eva-main#1]
~~I've noticed that some screw holes are missing in a couple of parts. The few I've noticed so far: The V6 shroud, core xy back (3 holes for universal cable mount), the universal cable mount itself is missing from the EVA 2 repositories, but is missing holes in newest EVA 1 as well. I will keep an eye out as i begin to print the EVA 2 parts and list them here.~~

Update: See discussion.

**Comment by pkucmus** [comment]
If you are talking about for e.g. those: 
![image](https://user-images.githubusercontent.com/6347418/99959228-e70c1e80-2d8a-11eb-8e66-c2cc91688d01.png)
then that's my ~time saving~ professional technique that allows the holes to be printed mid-air. One then needs to poke or drill the holes before assembly.

**Comment by miklschmidt** [comment]
@pkucmus ooooh. I see! Fair enough. I might've missed the memo on that one.

**Comment by pkucmus** [comment]
Still a valid note to self to document that. Thanks!

**Comment by miklschmidt** [comment]
@pkucmus i've updated the issue to reflect the needed change :)

**Comment by pkucmus** [comment]
Fixed: https://eva-3d.github.io/eva-main/printing/#pokey-pokey-hole-technique
