### ISSUE TITLE
EVA 2 / Orbiter (Orbiter support)

### ISSUE THREAD

**Issue by pkucmus** [EVA-3D/eva-main#10]
![eva_orbiter](https://user-images.githubusercontent.com/6347418/103447960-cb057200-4c92-11eb-835a-954cd740711b.png)

MGN 12: https://cad.onshape.com/documents/bb8303124bc8370b6d1924bc/w/8276a22c579374e8b02e9b96/e/6b8206d26df549409bc1d1b2

MGN 15: https://cad.onshape.com/documents/551442bc5664b4216eddf506/w/16749997681c8bec66757f15/e/8952ad2027c63b84e64fdcba

**Comment by pkucmus** [comment]
Added the Orbiter CR-10 version to both MGN12 and MGN15

**Comment by tetele** [comment]
Using this on a BLV MGN Cube with a Volcano 0.4mm nozzle. The assembly went great, as with all EVA components.

Here's a sample print at 0.2mm height, 80mm/s perimeter speed and 100mm/s infill speed. Acceleration 3000, except for external perimeter, which is capped at 300 for a better finish. Colorfabb economy PLA black @ 200deg

I could have gone higher with the acceleration, but I haven't really tuned it yet.

https://imgur.com/a/QLx88BT

![2021-01-19 12 23 15](https://user-images.githubusercontent.com/920098/105022222-2cc72980-5a52-11eb-83eb-567059ec2b95.jpg)

![2021-01-10 14 30 31](https://user-images.githubusercontent.com/920098/105022641-a9f29e80-5a52-11eb-9cb5-83a84fe4f81d.jpg)
