### ISSUE TITLE
Zero G Mercury 1.1 Support

### ISSUE THREAD

**Issue by emersonsc** [EVA-3D/eva-main#106]
Hoping you're able to officially add the Zero G Mercury 1.1 support like it had *unofficially* support on the 2.4.2 platform. Love the 3.0 look and design

**Comment by pkucmus** [comment]
This comes back from time to time. The gist of the compatibility is that it's the printer that needs to be compatible with EVA - not the other way around. Having designed EVA, V-Core3, V-Minion and Easy-Mod for V-Core Pro I can vouch that it's not that hard to achieve.

The reasoning behind that is that EVA already needs to adhere to all the standards, like hotends and drives shapes and sizes, different cooling, etc if I was ever to aim at printer compatibility it would a maintenance nightmare. Something has to give so the compatibility needs to go this way:
```
All the hotneds <--- EVA <--- Printers
All the drives  <--- 
All the cooling <---
...
```
This also makes sense as it's the printer that will benefit of integrating with EVA as the interface, Eva does not gain much from being compatible with more printers, it gains on being compatible with more hotends, etc. The printer gains as if it's EVA compatible it's automatically compatible with all that EVA brings.

That is my stance at least, I hope it makes sense.
