### ISSUE TITLE
BLTouch mount interferes with probe

### ISSUE THREAD

**Issue by shuffleznl** [EVA-3D/eva-main#11]
First of all, many thanks for a great design. Amazing work!

Quick one on the BLtouch Standard mount; the vertical overhang-reinforcement to support the horizontal BLtouch mount area interferes with the mounting 'flange' of the BLtouch itself.

It's only ever so slight, may just be 1mm off in the design.
![PXL_20210107_141730884 (2)_LI](https://user-images.githubusercontent.com/8324786/103903230-ec83b500-50fb-11eb-9362-39b2b89aedeb.jpg)

**Comment by pkucmus** [comment]
Thank you for the ticket, I'll look into it

**Comment by pkucmus** [comment]
Looking at the picture, there's a chance your printer is overextruding a bit but the lack of tolerance on the design is an issue I just fixed.
You can find the new part here:
https://cad.onshape.com/documents/94cafeab52e3dfa0a28bae89/w/99794094315556b24b5664ec/e/d6374a1e5b14711360d3b164

![image](https://user-images.githubusercontent.com/6347418/103938902-4354b300-512b-11eb-9866-d546e8e6e5c4.png)

Please let me know if it works.

**Comment by shuffleznl** [comment]
Extrusion still needs to be tuned yes :) Printed way too fast (💯mm/s) on 0.15 with very poor non-dried 'transparent' Amazon filament :). Currently still run V-Core (rails) w/o EasyMod and EVA, printed EVA components fit like a glove though, your design is awesome! Will print all again slower with Easy & EVA ❤️ 

Printing now.
