### ISSUE TITLE
duet tool bord

### ISSUE THREAD

**Issue by BenDiesel1** [EVA-3D/eva-main#111]
i was wondering if any one had a way of mounting a duet tool bord to the eva hot end system? im building a ratrig 500.

**Comment by olivbd** [comment]
What drive are you using? BMG, LGX, Orbiter... ?

**Comment by BenDiesel1** [comment]
we have the ldo obiter 2.0
thanks

**Comment by olivbd** [comment]
you can try this
https://www.printables.com/model/233448-duet-toolboard-1lc-mount-eva3-compatible

**Comment by BenDiesel1** [comment]
oh lol that works thanks
