### ISSUE TITLE
[BUG] The bolt that secures the endstop mount to the top plate hits the MGN carriage on the Orbiter assembly

### ISSUE THREAD

**Issue by tetele** [EVA-3D/eva-main#12]
## Describe the bug
Wrong offset between the bottom plane of the top piece and the lip of the endstop groove on the top piece (the groove is too close to the bottom).

## Actual behavior
The bolt that secures the endstop mount to the top plate hits the MGN carriage, so I can't secure the endstop mount to the top piece

## Expected behavior
I can screw in the bolt that secures the endstop mount to the top piece all the way, so that the endstop mount is rigid against the top piece.

## Pictures
https://imgur.com/a/RWgkyJs

## Device
 - EVA version: 2.1.1
 - Orbiter Assembly

**Comment by pkucmus** [comment]
Fixed, thank you: https://cad.onshape.com/documents/bb8303124bc8370b6d1924bc/w/8276a22c579374e8b02e9b96/e/09d4e72250a20923ab87fce6
