### ISSUE TITLE
Published STL's of the Bowden top does not fit MGN12H

### ISSUE THREAD

**Issue by rveda** [EVA-3D/eva-main#16]
## Describe the bug
Published STL's of the Bowden top does not fit MGN12H

## Actual behavior
The hole pattern matches MGN12C

## Expected behavior
The STL file to have the enlogated screw holes like in the CAD model.

## Pictures
I exported the top piece from the CAD model and compared it to the STL
![image](https://user-images.githubusercontent.com/1105428/104463957-b0949800-55b2-11eb-8d11-96289644fe11.png)

## Device
Hemera download and the complete download

**Comment by rveda** [comment]
Sorry. Didn't realize it was not released yet. You can close this Issue.

**Comment by pkucmus** [comment]
For future reference, the parts in question are yet to be released and I need to do a better job describing that the Onshape links are always bleeding edge.
