### ISSUE TITLE
[EP] Support for Sidewinder X1 Daughterboard / NF Crazy Hotend

### ISSUE THREAD

**Issue by nicedevil007** [EVA-3D/eva-main#18]
Heya just want to ask if you can create a "Sideplate" to mount the Artillery Sidewinder's Daugtherboard for the ribbon cable.

Besides the NF Crazy Hotend from Mellow I just wanted to ask if your version for the Mosquitto would be compatible?
The NF Crazy is a bit more as a triangle but the rest (cooling part) is the same from dimensions.

**Comment by pkucmus** [comment]
Widely understood support for the Sidewinder is not something I can tackle right now. NF Crazy is not officially supported but it may work by accident.

**Comment by top-gun** [comment]
The NF Crazy does work by accident :) I've been using one for a few weeks.
