### ISSUE TITLE
[EP] Support for Bondtech LGX

### ISSUE THREAD

**Issue by pkucmus** [EVA-3D/eva-main#19]
## Problem description
Bondtech is releasing this new (face heavy) extruder/hotend which is already of high demand. EVA should support it especially that @ogland already made the work for EVA 1.

## Describe the solution you'd like

General support for Bondtech LGX

### Functional and non-functional requirements
- as a first pass, port @ogland's work to EVA 2

### Proposed solution

None

### Considered Alternatives

None

### Additional context

None

**Comment by pkucmus** [comment]
Open for testing: https://cad.onshape.com/documents/d2a2f19b34851a8570487add/w/1ff9bb9662c715a9cdc3d984/e/f74cb56cf915933a84ff4023
![image](https://user-images.githubusercontent.com/6347418/112728707-d6caa280-8f28-11eb-9850-907fb3f908f9.png)

**Comment by ogland** [comment]
Looks good! Looking forward to seeing your approach to LGX FF.

**Comment by pkucmus** [comment]
@ogland I aim to port yours as well and release both

**Comment by pkucmus** [comment]
Would be cool if it was printable... don't print - there's still much work to do with this on.

**Comment by pkucmus** [comment]
Deployed in 2.3.0: https://main.eva-3d.page/drives/lgx/
