### ISSUE TITLE
Documentation: BMG drive docs link to titan top part.

### ISSUE THREAD

**Issue by miklschmidt** [EVA-3D/eva-main#2]
See: https://eva-3d.github.io/eva-main/drives/bmg/
![Screenshot_69](https://user-images.githubusercontent.com/751171/100031479-0be9ab80-2df6-11eb-9faf-e52ef455a49f.png)

**Comment by pkucmus** [comment]
It's good catch. It's actually a bmg part, just the name is wrong.

**Comment by pkucmus** [comment]
Fixed: https://eva-3d.github.io/eva-main/drives/bmg/
