### ISSUE TITLE
Volcano Bltouch

### ISSUE THREAD

**Issue by churd83** [EVA-3D/eva-main#22]
Great job on this mod, but there is no mount for the BLtouch that accomodates the Volcano hotend.

**Comment by pkucmus** [comment]
Noted, next time please use the issue template.

**Comment by pkucmus** [comment]
Proposed fix

![image](https://user-images.githubusercontent.com/6347418/110211307-53241580-7e96-11eb-9e60-48120506847e.png)
![image](https://user-images.githubusercontent.com/6347418/110211313-57503300-7e96-11eb-9475-867aaaf1b1e3.png)
https://cad.onshape.com/documents/94cafeab52e3dfa0a28bae89/w/99794094315556b24b5664ec/e/d6374a1e5b14711360d3b164
