### ISSUE TITLE
Looking for an older version of files

### ISSUE THREAD

**Issue by nesdnuma** [EVA-3D/eva-main#23]
Hello,

I got pieces printer for a BMG-M + Mosquito configuration adapted to the pre-2.0 version. Now I am going to assemble it.  Can you tell me where the instructions for this version are?

**Comment by pkucmus** [comment]
You can find the documentation for EVA 1.x.x here: https://pkucmus.github.io/EVA/

**Comment by nesdnuma** [comment]
Thanks a lot!
