### ISSUE TITLE
[EP] Mosquito-face: Shield heatblock from coldend-fan

### ISSUE THREAD

**Issue by top-gun** [EVA-3D/eva-main#26]
## Problem description
On the Mosquito mount, I found that the heatblock runs into thermal issues with strong fans for the coldend. It is possible to overcome this by PWM-reducing the fan performance, but that's not possible with any mainboard, and it is bad for the fan. In fact, the fan is not the problem. It is a gap in the face-part that lets air escape freely downwards where it is not supposed to go.

## Describe the solution you'd like

Change the face-part so it shields the heatblock better from airflow.

Short summary of what you want to happen.

Close the gap at the bottom of the Mosquito-face

### Functional and non-functional requirements
nothing, this is just a minor change to an existing CAD-designed part

### Proposed solution

On the sides of the gap, there are surfaces on the mount that directly face each other. An extrusion on one of these surfaces that extends over the whole gap and reduces the down-facing air-stream considerably. With this modification, I was able to reach 265°C hotend temperature and to PID-tune at 260° without more thermal-runoffs.

### Considered Alternatives
None, I think this is the easiest solution.

### Additional context
There are also unecessary gaps on the support-part, but I can't close them well. 
[Mosuito-face.zip](https://github.com/EVA-3D/eva-main/files/6031597/Mosuito-face.zip)

**Comment by pkucmus** [comment]
I applied the fix @top-gun made to the face, did not apply the support part change: 
https://cad.onshape.com/documents/1765b04fac582f6c1c470bd3/w/1cc31596374d6ce51cd23fa9/e/71691e38db5265f268854a02
