### ISSUE TITLE
[FR] Sherpa Mini support

### ISSUE THREAD

**Issue by msource** [EVA-3D/eva-main#31]
## Problem description
Support on EVA2 for Sherpa Mini

## Describe the solution you'd like
Support on EVA2 for Sherpa Mini

### Additional context
https://github.com/Annex-Engineering/Sherpa_Mini-Extruder

**Comment by pkucmus** [comment]
@msource do you have a supplier to recommend? Where can I get one?

**Comment by msource** [comment]
Yes Sir:
https://a.aliexpress.com/_mqp85jV

**Comment by lowtolerance** [comment]
Is it safe to say this issue can be closed now that EVA 2.4 has an official Sherpa Mini top?
