### ISSUE TITLE
Nut clearance at join of "universal face" and "bottom_mgn12_short_duct"

### ISSUE THREAD

**Issue by pman92** [EVA-3D/eva-main#32]
The captive nut hex shape at the bottom of "universal_face.stl" is too short for a M3 nut to be fully pulled in flush. It sticks out and prevents "bottom_mgn12_short_duct.stl" from mating properly. This nut is used to secure "v6_support.stl".

There is room in "bottom_mgn12_short_duct.stl" to provide a clearance hole so the bolt and nut could both protrude into them. 

[image](https://imgur.com/a/jIgDy7Z)

**Comment by silvalis** [comment]
As per the duct alignment issue, you've printer the incorrect bottom_mgn12_short_duct. The one in the orbiter fileset has a cutout to allow clearance for the nut and screw.

**Comment by pkucmus** [comment]
There might be an issue with the stl directory in the root of the project, in the image bellow you'll find a preview of the proper file: 
![image](https://user-images.githubusercontent.com/6347418/111874245-9309f300-8994-11eb-9b51-53394aae6d6a.png)
https://cad.onshape.com/documents/1765b04fac582f6c1c470bd3/w/1cc31596374d6ce51cd23fa9/e/bf748cd402ac505d88311d6e

**Comment by pkucmus** [comment]
It was a filename issue it's fixed in: https://github.com/EVA-3D/eva-main/commit/0f7b9bcc789e196c75741722d1397ba23493656d
Thanks
