### ISSUE TITLE
[EP] Wider cooling duct to stop warp on mosquito hotends

### ISSUE THREAD

**Issue by bionicmunky** [EVA-3D/eva-main#36]
## Problem description
I find that the duct end is prone to warping with the mosquito as the heat block is wider compared to V6

## Describe the solution you'd like

A slightly wider gap between prongs to stop the duct warping with Mosquito

**Comment by pkucmus** [comment]
Just deployed 2.3.0, please check out https://main.eva-3d.page/addons/fan-ducts/
