### ISSUE TITLE
[EP]tension_slider tooth

### ISSUE THREAD

**Issue by vozik** [EVA-3D/eva-main#39]
My steppers are in the front not in the back. This couses that the tension_slider tooth is on the wrong side.
teeth should be on the inner wall?

**Comment by vozik** [comment]
Not common, but some printers have front steppers. For these, the inner tooth on the tensioner would be good. the front holds the other way too.

**Comment by silvalis** [comment]
Do you flip your belts at the back?

**Comment by vozik** [comment]
> Do you flip your belts at the back?

No. It is a good idea. I Will change the pulleys (Back pulleys are toothed) and flip the belts. Thanks.
