### ISSUE TITLE
[EP] mgn9 support

### ISSUE THREAD

**Issue by EduardoOliveira** [EVA-3D/eva-main#41]
## Problem description
Lowering the weight even more with mgn9 on the x rail

## Describe the solution you'd like

The possibility to use mgn9 out of the box

### Functional and non-functional requirements
- mgn9 (h?) compatible holes
- printable shims to make for the height difference

### Proposed solution

Increase the slot size if possible to accommodate mgn9 and possible shim height difference

### Additional context
I know its a its some work, but I'm just kicking the idea out there, some us have been drooling over "that other awesome project" that is fast as hell and uses EVA. I don't mind making another version of the XY joinners for mgn9 and possible carbon fiber base axis

**Comment by arne182** [comment]
I will be going to do this. The MGN9 H is a must as the C is too narrow in my opinion for the distributed weight of the extruder. I am also looking into the CF tube:
https://hobbyking.com/en_us/carbon-fibre-square-tube-20-x-20-x-800mm.html
Shims are not a bad idea for the start but I am planning on reprinting all the parts in PA-CF to get them more temperature resistant.
