### ISSUE TITLE
Incorrect files ..

### ISSUE THREAD

**Issue by themacboy** [EVA-3D/eva-main#42]
In the "stl.zip" the file "bottom_mgn12_short_duct.stl" looks like a incorrect version.

![image](https://user-images.githubusercontent.com/8063711/115973589-7e51e980-a556-11eb-8165-f3092d9b30de.png)

Download linl:
https://github.com/EVA-3D/eva-main/raw/2.2.1/stls.zip

File preview:
![image](https://user-images.githubusercontent.com/8063711/115973610-ae00f180-a556-11eb-94d9-965b0b5c2907.png)

But must be:
![image](https://user-images.githubusercontent.com/8063711/115973623-c6710c00-a556-11eb-8ec4-21684de51cb3.png)

Im correct? Thx in advance ! Great project !

**Comment by pkucmus** [comment]
I'm about to deploy 2.3.0 today, wrote a lot of code that should do all this automagically so I hope those mistakes will not happen again (taking human error out of the equation)

**Comment by pkucmus** [comment]
Deployed, please let me know if something if not right
