### ISSUE TITLE
Cartesian and Idex blower [EP]

### ISSUE THREAD

**Issue by themacboy** [EVA-3D/eva-main#43]
First of all, I'm sorry to post it here, but the Cartesian repository looks close to post issues.

I noticed than cartesian and idex design use the 5015 blower, and it is too large to fit in my Ender 5 Plus, and probalbly others. 

I like to know if is possible to get a blower 4020 version. (never used onshapes, currently learning FreeCad)

Or if it is compatible to use the coreXY version.

Thx in advance ! Great work, soon I will post my pictures.

**Comment by pkucmus** [comment]
I'll look for a guy who put EVA on an Ender 5 to he if he can help

**Comment by pkucmus** [comment]
Also this is a perfect place for those "EPs" :)

**Comment by vellkan** [comment]
> First of all, I'm sorry to post it here, but the Cartesian repository looks close to post issues.
> 
> I noticed than cartesian and idex design use the 5015 blower, and it is too large to fit in my Ender 5 Plus, and probalbly others.
> 
> I like to know if is possible to get a blower 4020 version. (never used onshapes, currently learning FreeCad)
> 
> Or if it is compatible to use the coreXY version.
> 
> Thx in advance ! Great work, soon I will post my pictures.

Hi :)
You've got problem with back plate fan, correct? On repository is slim version for 5015 fan, but event with that You need to move endstop.
I've got this in Ender 5 Pro, I just move endstop a little and now everything is fine. I can provide You some photos if You want.

**Comment by themacboy** [comment]
Yes, sure. And a lot of Thx

**Comment by themacboy** [comment]
Where is the slim version?

**Comment by vellkan** [comment]
As I understand You've got this problem, yes?
This is version with slim back plate, but still can hit to this metal parts. I just moved Y endstop to the front.
Yes, I lost about 2cmm of bed in Y axis, but can live with that :)


![IMG_20210426_144800](https://user-images.githubusercontent.com/2522756/116084966-9fbded00-a69e-11eb-834a-4bad907b73ff.jpg)
![IMG_20210426_144748](https://user-images.githubusercontent.com/2522756/116084970-a0568380-a69e-11eb-89e4-f54097bdd887.jpg)
![IMG_20210426_144653](https://user-images.githubusercontent.com/2522756/116084971-a0ef1a00-a69e-11eb-9c6b-81b7caf5c7aa.jpg)

**Comment by themacboy** [comment]
+1

**Comment by vellkan** [comment]
I found it on Discord channel, but I will upload it on OneDrive:
https://1drv.ms/u/s!AglN16Zy9Yb1pmkzyMej11izTrnm?e=GsXgku

**Comment by themacboy** [comment]
Lot of Thx

**Comment by pkucmus** [comment]
I'll assume this one is closed
