### ISSUE TITLE
[BUG] Wrong CAD link to Catesian support

### ISSUE THREAD

**Issue by flow23** [EVA-3D/eva-main#45]
## Describe the bug
Go to https://main.eva-3d.page/addons/cartesian_idex/ and click on CAD

## Actual behavior
Opens CAD drawing of x endstops

## Expected behavior
Opens CAD of Cartesian support

## Pictures
X

## Device
X

## Additional context
X

**Comment by pkucmus** [comment]
Thank you! It's fixed (will get deployed in around 10 minutes)
