### ISSUE TITLE
[BUG] Belt indentation inside cartesian back

### ISSUE THREAD

**Issue by flow23** [EVA-3D/eva-main#46]
## Describe the bug
Belt indentation inside cartesian back.

## Actual behavior
Belt indentation inside cartesian back.

## Expected behavior
No belt indentation inside cartesion back because the belt is secured by two belt blocks in the back.

## Pictures
https://cad.onshape.com/documents/a2d21b0faa4745fa21bc844e/w/d7f14dfeeee2e68fe2f1149b/e/fcd1503d3995b7b7473cc831

## Device
X

## Additional context
X

**Comment by pkucmus** [comment]
I am sorry but I will require this ticket to be more descriptive as I have no idea what this is supposed to achieve

**Comment by flow23** [comment]
I was wondering if this feature is really needed for cartesian printers? I thought that the belts are tentioned by the two blocks in the back. Maybe I misunderstood the CAD drawing.
<img width="594" alt="Screenshot 2021-05-16 at 12 06 58" src="https://user-images.githubusercontent.com/3601005/118393437-7231e700-b63f-11eb-8df2-4bef88772cd0.png">

**Comment by EduardoOliveira** [comment]
In any configuration each belt has a tip that goes into a tensioning block and another tip that is held statically to the carriage.
In CoreXY systems one of the tips is held by the block in the back and the other tip is held in the front.
In Carterian systems the static tip is held by that groove and the other tip by the block

Having 2 tensioner blocks in a single belt would be redundant at best

Did I make it clearer? If you have any doubt you can  reach out on discord

**Comment by flow23** [comment]
Understood.
