### ISSUE TITLE
[BUG] Website - top_endstop_plug_mgn12.stl missing in 2.3.0

### ISSUE THREAD

**Issue by Mitsuma** [EVA-3D/eva-main#47]
## Describe the bug
I was looking at the X Endstop section https://main.eva-3d.page/addons/x_endstop/ and noticed that the link for the file is giving a 404: https://main.eva-3d.page/stls/top_endstop_plug_mgn12.stl

It appears that it is missing from the 2.3.0 branch as it is not in the https://github.com/EVA-3D/eva-main/tree/main/stls folder.
Not sure if this is intended but seeing the others are still there, including the bigger MGN15 version I think this is an oversight.

You can still find it in the older 2.2.1 branch: https://github.com/EVA-3D/eva-main/blob/2.2.1/stls/top_endstop_plug_mgn12.stl
(Not sure if that part was changed from 2.2.1 to 2.3.0

**Comment by pkucmus** [comment]
solved in 2.4.0
