### ISSUE TITLE
[BUG] CoreXY back missing sacrificial layer

### ISSUE THREAD

**Issue by jerejones** [EVA-3D/eva-main#51]
## Describe the bug
The hole used to secure the fan on the CoreXY back is missing a sacrificial layer.

## Actual behavior
The print ends up very ugly inside that hole when it tries to print without supports

## Expected behavior
I would expect a sacrificial layer so that the slicer will bridge cleanly

**Comment by pkucmus** [comment]
Thanks this is fixed in the [CAD](https://cad.onshape.com/documents/1765b04fac582f6c1c470bd3/w/1cc31596374d6ce51cd23fa9/e/570a5d066d5942fa3f78b745) already. Will get deployed with 2.4.0
