### ISSUE TITLE
[BUG] Sensorless endstop file link leads to 404

### ISSUE THREAD

**Issue by Hajto** [EVA-3D/eva-main#54]
## Describe the bug
404 when trying to download sensorless endsto
https://main.eva-3d.page/stls/top_endstop_plug_mgn12.stl

## Actual behavior
404

## Expected behavior
Download the file

## Pictures
<img width="1547" alt="Zrzut ekranu 2021-07-11 o 10 54 22" src="https://user-images.githubusercontent.com/8336429/125188996-67a65f00-e236-11eb-9088-1f6cb3893c46.png">

**Comment by nfruge56** [comment]
For anyone looking for the file, until the link is fixed, they can go to the 2.2 branch and download the top_endstop_plug_mgn12 file from the STLs folder.

**Comment by pkucmus** [comment]
solved in 2.4.0
