### ISSUE TITLE
[EP] Make cooling options machine independent

### ISSUE THREAD

**Issue by forerunnert** [EVA-3D/eva-main#55]
## Problem description

I think EVA is a fantastic idea and I plan to fit it onto my BLV MGN cube in the near future.
Ideally it would include a Volcano hotend and a dual 5015 blower too.

All these options exist as community contributions but they cannot be used together as the fan mounting points and part of the duct is integrated into the back plate.

## Describe the solution you'd like

I'd like to see the cooling (fan mount and duct) removed from the back plate and replaced by an interface. 
This way the cooling options are not restrained anymore and can be mixed and matched with different back plates for different machines.

### Functional and non-functional requirements
- universal fan interface on backplate
- universal fan duct interface on back plate

### Proposed solution

[https://postimg.cc/hX5wfGxr](url)

### Considered Alternatives
I could take the step files of the relevant parts and make a 'for BLV' version and contribute that. 
This would however create additional versions of identical parts while the whole EVA project is an opportunity to avoid just this situation:

    - 'EVA conversion kit for BLV MGN Cube' => 'EVA conversion kit for BLV MGN Cube and Volcano and dual 5015'
    - 'Horns Duct v2 variant for E3D Volcano' => 'Horns Duct v2 variant for E3D Volcano for BLV'
    - 'SuperSniffles' Dual 5015 Part Fan Mod' => 'SuperSniffles' Dual 5015 Part Fan Mod for BLV'

**Comment by pkucmus** [comment]
This is interesting. Not sure yet how to approach this and it will take time but I'll think about it more. For now making a forked back part is the way to go.
