### ISSUE TITLE
[EP] Change hole shape to make nut insertion into printed pieces easier

### ISSUE THREAD

**Issue by nesdnuma** [EVA-3D/eva-main#58]
## Problem description
Insertion of nuts in printed pieces (especially small M3 nuts) can be a real pain, especially if there's not a flat surface around the hole. Sometimes one has to push very hard to put the nut in place. Moreover, when the holes are deeper than the nut height, it's hard to know when to stop pushing with the risk of breaking a printed part.

## Describe the solution you'd like

Make the holes in such a way that the insertion of the nuts are easier.

### Proposed solution

Change the shape of the holes. Only make the hole tight at the very end where the nut is supposed to stay. Otherwise make the upper part of the hole broader. Here are three different design profiles (#2 is my favourite).

Profile 1:

![Profile version 1](https://user-images.githubusercontent.com/6513218/129748018-f3a4a2cf-6c41-4ffe-bda9-368484a8b4e8.png) ![Rendering version 1](https://user-images.githubusercontent.com/6513218/129748025-8e31ed7d-7237-44da-9365-b0be1e9687d6.JPG)

Profile 2:

![Profile version 2](https://user-images.githubusercontent.com/6513218/129748022-5a12a2e5-fcc5-4993-8073-b2e52df764db.png) ![Rendering version 2](https://user-images.githubusercontent.com/6513218/129748027-9c1357a8-033a-405d-86e4-3ffc80f32336.JPG)

Profile 3:

![Profile version 3](https://user-images.githubusercontent.com/6513218/129748023-4c564fff-acbb-42fd-bdcd-c5aba8bf8c71.png) ![Rendering version 3](https://user-images.githubusercontent.com/6513218/129748029-ba5f15b8-8b8a-45a5-a81f-7f0d2eae9afc.JPG)

**Comment by nesdnuma** [comment]
No one's reading? :-(

**Comment by EduardoOliveira** [comment]
Hi, have you tried pulling the nut into place by inserting a screw into the hole and thightening it into place?
That's what I usually do with a screw that's only the dept of the hole plus 3 or 4mm to grab the nut, after the nut is pulled into place i remove the screw and proceed with he assembly.

I know your suggestions simplifies the process but adds some work and provable collisions there the nut holes are close to other features.

**Comment by pkucmus** [comment]
Thanks for the EP.
I honestly don't see the need for this, moreover, this is flawed as prone to alignment errors. One should not fit the nuts and after that thread the screws - we had a lot of issues with nut binding in the early days.
The proper way to seat a nut is with by ["backpulling"](https://main.eva-3d.page/printing/#handling-hex-nuts) this ensures that a nut will be driven into the socket on the angle the screw will want the nut to be.

**Comment by nesdnuma** [comment]
For deep holes I still think it would be really useful and would not create alignment issues as the bottom of the hole is tight.  I have re-discovered backpulling on my side while building a V-Core Pro but the page you've linked to should be included in each Ratrig assembly documentation @pkucmus !

**Comment by pkucmus** [comment]
It is on the one manual I made: https://ratrig.dozuki.com/Guide/00.+Preparations/78?lang=en#s477 
as for the rest, sure just let Rat Rig know :)
