### ISSUE TITLE
[Bug]: Dragon Hotend CAD Link has incorrect OnShape Link

### ISSUE THREAD

**Issue by LordNed** [EVA-3D/eva-main#65]
### Discord username

Matt "@LordNed" Hoffman#3445

### What happened?

If you try to use the "CAD" link at the bottom of the Dragon Hotend page (https://main.eva-3d.page/hotends/dragon/) it tries to take you to https://cad.onshape.com/documents/1765b04fac582f6c1c470bd3/w/1cc31596374d6ce51cd23fa9/e/f85b6fffa3072e3e42bb94c9 for the Onshape document. However when loading that page, you get an error message that says "Can't open tab. The tab does not exist in this document workspace." and then the cad model shown is a blower.

### EVA Version

2.3.0

### Which printer are you using?

V-Core 3

### Terms

- [X] I did seek help on Discord and found none or was instructed that this is indeed an EVA bug.

**Comment by pkucmus** [comment]
solved in 2.4.0
