### ISSUE TITLE
[Bug]: Eva 2.4.0 mounting holes for belt 

### ISSUE THREAD

**Issue by Jegstrup** [EVA-3D/eva-main#67]
### Discord username

Noobie4ever

### What happened?

hi 

when trying to mount belt on a sapphire plus the belt slider need to bee invertet otherwise the belt will be twistes any solution for this ? 

### EVA Version

2.4.0

### Which printer are you using?

Other

### Terms

- [X] I did seek help on Discord and found none or was instructed that this is indeed an EVA bug.

**Comment by Jegstrup** [comment]
i did manage to solve it kind off :D it will work if i turn toolhead 180 degrees but prefer to have it like i should be

**Comment by pkucmus** [comment]
So you just need tensioner blocks that would have the teeth on the other side?

**Comment by Jegstrup** [comment]
Exactly. 😊

søn. d. 2. jan. 2022 22.25 skrev Paweł Kucmus ***@***.***>:

**Comment by psusong** [comment]
<img width="200" alt="m5" src="https://user-images.githubusercontent.com/9137231/152469972-abe32381-93e1-4596-8ff1-d08319f3ffe3.png">
only yes no no i searched all the stl

**Comment by psusong** [comment]
Only tension_slider_9mm_belt_M5.stl
no opposite

**Comment by pkucmus** [comment]
I'm closing this one as EVA 3 is here and I can't take on printer compatibility work, best to ask on Discord, a bunch of people there will be able to make adjustments
