### ISSUE TITLE
[Bug]: incorrect PTFE tube length for LGX + V6 combo

### ISSUE THREAD

**Issue by blalor** [EVA-3D/eva-main#69]
### Discord username

yolo-dubstep#8033

### What happened?

Combined PTFE tube length (46.9mm) of LGX drive ([13.8mm](https://main.eva-3d.page/drives/lgx/#bill-of-materials)) and V6 hotend ([33.1mm](https://main.eva-3d.page/hotends/v6/#bill-of-materials)) appears to be too short.  When assembling my extruder I found that ~55mm is closer to correct, with the tube passing through the LGX coupler to make contact with the body, and fully inserted into the V6 heatsink until it stops.

### EVA Version

2.4.1

### Which printer are you using?

V-Core 3

### Terms

- [X] I did seek help on Discord and found none or was instructed that this is indeed an EVA bug.

**Comment by blalor** [comment]
cut per spec:
![IMG_4861](https://user-images.githubusercontent.com/109915/147684230-91d0e621-ffe0-4ab4-be95-11cd8ce93ec8.jpg)

what I'm using:
![IMG_4862](https://user-images.githubusercontent.com/109915/147684233-3028f9c3-ac8e-4f88-89e1-440c416d60e0.jpg)

**Comment by pkucmus** [comment]
Thanks, fixed in 2.4.2, the model for LGX did not assume us shoving the PTFE so deep, I measured my LGX and made changes to the model I hope it'll be correct now.
