### ISSUE TITLE
Toolboard support

### ISSUE THREAD

**Issue by pkucmus** [EVA-3D/eva-main#7]
Moved from EVA 1 https://github.com/pkucmus/EVA/issues/24

**Comment by philkry** [comment]
@pkucmus do you have a plan already on when this will get implemented? 
Or is there maybe some bleeding-edge version available to test?

**Comment by pkucmus** [comment]
@philkry I'm working on the 2.2.0 release currently, this is meant for 2.3.0

**Comment by pkucmus** [comment]
@philkry I found the previous attempts we tried: https://cad.onshape.com/documents/bbefa7dc6aa8749d2947b610/w/f35b0df99ac53a3b3afd0ae4/e/8b3fb665196e336e4b59316d maybe you'll find something usable
