### ISSUE TITLE
[Bug]: Duct for LGX is different than the others

### ISSUE THREAD

**Issue by blalor** [EVA-3D/eva-main#70]
### Discord username

yolo-dubstep#8033

### What happened?

Screenshots below from PrusaSlicer. The one highlighted in green is `TriHorn Duct.stl` from the [LGX drive page](https://main.eva-3d.page/drives/lgx/#bill-of-materials). The other two from the top are `TriHorn Duct Default.stl` and `TriHorn Duct Wide Low.stl`.

<img width="667" alt="Screen Shot 2021-12-31 at 6 41 35 AM" src="https://user-images.githubusercontent.com/109915/147822445-41a41c03-bcce-469e-88ed-5c70c78eba60.png">
<img width="628" alt="Screen Shot 2021-12-31 at 6 41 46 AM" src="https://user-images.githubusercontent.com/109915/147822446-4d3dc596-68c5-40a4-86d6-a53c00dc332e.png">
<img width="859" alt="Screen Shot 2021-12-31 at 6 49 42 AM" src="https://user-images.githubusercontent.com/109915/147822442-f39aed89-d7e8-49e6-87ef-ec027fe8f964.png">
<img width="867" alt="Screen Shot 2021-12-31 at 6 49 52 AM" src="https://user-images.githubusercontent.com/109915/147822443-900046e6-e96f-46e8-8517-422ce7388bb0.png">
<img width="860" alt="Screen Shot 2021-12-31 at 6 50 03 AM" src="https://user-images.githubusercontent.com/109915/147822444-a6e75295-ff06-45e8-b885-2baadacd379b.png">

The widest LGX-sourced duct interferes with the Euclid probe, which is how I discovered the problem. The existence of the LGX-sourced duct is not an issue (some may find it useful?) but it being different from the others without commentary or being included with the others in the layer cooling section _is_ an issue.

### EVA Version

2.4.1

### Which printer are you using?

V-Core 3

**Comment by pkucmus** [comment]
Thanks, fixed in 2.4.2
