### ISSUE TITLE
[EP] EVA 2.4 -> Missing MGN15 support

### ISSUE THREAD

**Issue by guiguijke** [EVA-3D/eva-main#71]
## Problem description
Hello , I'm a VCAST owner and would like to migrate to your 2.4 version . However, I'm not able to do so because there is no MGN15 support for BMG mount.

## Describe the solution you'd like
Can you please continue to support such rail ?

### Functional and non-functional requirements & proposed solution
- top_bmg_mgn12 -> top_bmg_mgn15
- bottom_mgn12_short_duct -> bottom_mgn15_short_duct

**Comment by pkucmus** [comment]
I am unable to consume the amount of work that is required to support both. But I have two solutions for you:
1. Wait for the V-Cast 1.5 update
2. Use the 2.3 version of the BMG mount you can find the `top` and `bottom` files here, those will be compatible with the new `universal_front` and the new `back` [2.3.0 BMG files are here](https://github.com/EVA-3D/eva-bmg/tree/c984e1e64691c87fa68022beefe8df9648ca6bdb/stls)
