### ISSUE TITLE
[Bug]: TriHorn Duct Safe.stl is a 1KB file

### ISSUE THREAD

**Issue by weust1979** [EVA-3D/eva-main#75]
### Discord username

weust#0214

### What happened?

Checking out the STL files for the ducts and noticed "TriHorn Duct Safe.stl" is a 1KB file.
Bad upload perhaps, somehow?

Location: stls\addons\layer_cooling\stls

### EVA Version

2.4.0

### Terms

- [X] I did seek help on Discord and found none or was instructed that this is indeed an EVA bug.

**Comment by pkucmus** [comment]
Killing this as it's EVA 2.4
