### ISSUE TITLE
Was support for the Dragon hotend removed?

### ISSUE THREAD

**Issue by atomicwrites** [EVA-3D/eva-main#77]
I remember seeing the dragon in the list of hotends before, but it's gone now sometimes, or sometimes it's listed in the sidebar but the link 404s. I do see it in the v2.4.2 branch though. was this intentional?

**Comment by EduardoOliveira** [comment]
Hi, official support was removed in version 3, in version 2.4 you should still be able to download directly from CAD

**Comment by intelinc** [comment]
Bump. Just looking for this on 3.0.

**Comment by rjorgenson** [comment]
This was mentioned in the announcement stream, they will not be supporting the Dragon hotend.

**Comment by atomicwrites** [comment]
Not sure what's going on because I can't see it on the web UI, but I got this reply in an email:

> Hi, official support was removed in version 3, in version 2.4 you should still be able to download directly from CAD

**Comment by rjorgenson** [comment]
> Not sure what's going on because I can't see it on the web UI, but I got this reply in an email:
> 
> > Hi, official support was removed in version 3, in version 2.4 you should still be able to download directly from CAD

The 2.4 version is here in the git repo https://github.com/EVA-3D/eva-main/tree/release/2.4.2/stls/hotends/dragon under the 2.4.2 release.

**Comment by proap** [comment]
would the BMO mount work if we screw the BMO collar for the Dragon hotend?

**Comment by pkucmus** [comment]
> Not sure what's going on because I can't see it on the web UI, but I got this reply in an email:
> 
> > Hi, official support was removed in version 3, in version 2.4 you should still be able to download directly from CAD

Who did you e-mail? EVA is just me and I did not wrote that :|

**Comment by pkucmus** [comment]
The answer is here: https://main.eva-3d.page/FAQ/#dragon-support-clones-in-general 
I'll close this issue now :)
