### ISSUE TITLE
CAD Conflict

### ISSUE THREAD

**Issue by MicRood** [EVA-3D/eva-main#79]
The [Chonky Shroud](https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/8d0157f74965ce8e585dfb2d) Interferes with the [BL Touch](https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/dbf188e21e46a24ca801cc78) majorly and with the [Hex Nut CoreXY Core](https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/2f4214235ff3476304094ba7) slightly in EVA 3.0
![BL Touch Body](https://i.imgur.com/LC2VHZc.png)
![BL Touch Flange And Core](https://i.imgur.com/CFvSrgp.png)

**Comment by pkucmus** [comment]
BL-Touch will get it's own shroud if there's enough interest, for now it's not something I can fix
