### ISSUE TITLE
EVA3.0-rc1 5051 fan ducts are slightly too tight

### ISSUE THREAD

**Issue by mikejwaters** [EVA-3D/eva-main#82]
With a little grinding, I can fit my Winsinn fans, but my Delta fans won't line up. I think an extra 0.5 mm in the vertical direction (of these photos will make them fit easily. 
![IMG_20220517_095656](https://user-images.githubusercontent.com/19199709/168844115-e027d7bb-19df-4774-84db-896475c01d37.jpg)
![IMG_20220517_095906](https://user-images.githubusercontent.com/19199709/168844129-c487143f-8776-47d7-ba90-ce999210a603.jpg)

**Comment by mikejwaters** [comment]
Update: I shaved off more plastic and jammed the delta fans in place.

**Comment by pkucmus** [comment]
Fixed in 3.0
