### ISSUE TITLE
LGX mount interferes with the bottom of the LGX

### ISSUE THREAD

**Issue by mikejwaters** [EVA-3D/eva-main#84]
Hi again, 

The LGX has two protruding ovals that don't let it sit flat on the current LGX bracket. Here's a picture:
![2022-05-18 00 59 12](https://user-images.githubusercontent.com/19199709/169136056-1d4b138b-96c7-4ff0-a07e-e4491e00d764.jpg)

Bondtech provides .STEP files at the bottom of their product page which should help with fixing the issue: https://www.bondtech.se/product/lgx-large-gears-extruder/

**Comment by MidnightLink** [comment]
You're using the wrong interface. You want to use the one that has the bowden adaptor on it and remove the adaptor

**Comment by mikejwaters** [comment]
Yeap, the Bowden adapter fits perfectly. My mistake. Issue closed.
