### ISSUE TITLE
Request. E3d Revo Voron mount

### ISSUE THREAD

**Issue by midicdj1000** [EVA-3D/eva-main#85]
Hi, Will an EVA 3 mount for the E3d Revo Voron be in the future  ? It's not the same as the BMO.
https://e3d-online.com/blogs/news/revo-voron-available-now
I am just printing a BMO set at the moment in PC CF and it looks fantastic

**Comment by midicdj1000** [comment]
HI, I just saw that I can download the step file so I can edit in 123design my normal cad software. if I make my own parts for my diy printer what should I do so others can use ? I just made the top part with limit switch to fit my mgn12H part instead of the mgn12c for example.

**Comment by pkucmus** [comment]
I just purchased a Revo Voron with donation money, I'll make the mount for it soon

**Comment by midicdj1000** [comment]
Thanks, I am almost finished with this EVA3 for a dragonfly. I printed in Prsament PC CF and Esun silver PETG
![FT8jl-4WQAAdYmR](https://user-images.githubusercontent.com/30492351/170987411-6b3332fc-23a5-422b-850d-aafa918a1485.jpg)
![FT8jlqnWYAEBwrN](https://user-images.githubusercontent.com/30492351/170987422-79abf133-b1cf-424a-83e9-d39a8f1159bf.jpg)
![FT8jm0GWAAEswJq](https://user-images.githubusercontent.com/30492351/170987434-b95e5ecf-df04-466d-a9dd-b639148a0362.jpg)
![FT8jmYuWYAAEICR](https://user-images.githubusercontent.com/30492351/170987460-7133cae0-8de8-434b-8793-30357515c603.jpg)

**Comment by pkucmus** [comment]
Released: https://main.eva-3d.page/heat_insert/hotend/revo_voron/

**Comment by midicdj1000** [comment]
Thank you. What is the link to send you a small donation ?
