### ISSUE TITLE
EVA 3 Orbiter 1.5 hits the cable Guide.

### ISSUE THREAD

**Issue by b33k-WA** [EVA-3D/eva-main#86]
The cable guide cage hits the back end of my orbiter 1.5, if the cable guide bottom mounting hole was 40mm higher it would clear the top of the the motor or if it were rotated to mount face backwards rather than sideways.

**Comment by pkucmus** [comment]
CAD-wise it seems ok, it is too close to be immune to real-life errors but there is a question of how big of an issue it is. I'm going to mark it as won't fix but please feel free to let me know here if it's a deal breaked issue.
![image](https://user-images.githubusercontent.com/6347418/176964258-85b478b4-2ede-4844-8c56-a35a90f15dc2.png)
