### ISSUE TITLE
EVA 3 - Single 5015 - Not enough clearance

### ISSUE THREAD

**Issue by samsonnguyen** [EVA-3D/eva-main#88]
EVA3 with a single 5015 cooling fan

The width between the stems of the single 5015 inlet is measuring exactly 15mm from the onshape files.
Unfortunately, measuring a Sunon 5015 maglev fan, the width of the fan casing is 15.15mm +/- 0.1mm. Hence it is not possible to slide the fan into the inlet without significant strain or modifications like sanding the stems manually.

Additionally, due to printing tolerances and slight warping when printing in ASA. The width of my printed part varies between 14.9mm to 15.2mm. I printed this part vertically as shown in the "How to print" documentation.

Overall, it would be great to have more clearance to accomodate:
* Slightly oversized fan casings
* Printing tolerances
* Plastic warping during print (especially if using ABS or ASA)

![image](https://user-images.githubusercontent.com/452499/173759769-0288b2d4-7d91-4282-9f64-cca00ca600f2.png)

**Comment by pkucmus** [comment]
This was fixed in 3.0.1
