### ISSUE TITLE
EVA2 - BLtouch mount for short hotends

### ISSUE THREAD

**Issue by jbjhjm** [EVA-3D/eva-main#89]
about a week ago there was a discussion in RatRig community because someones BLtouch tip was destroyed several times when a print failed and produced some mess.
I just upgraded my EVA to a Dragon HF and realized it is really short. Even with the BLtouch screwed all the way to it's mount, the retracted tip will be pretty much on one level with the nozzle, so pretty much exposed and vulnerable to damage.

I created a simple remix of the EVA (2.4) BLtouch socket which will allow the probe to be mounted 5mm higher so that it is mounted in relative safety. The Zip contains STEP and STL files. Don't know if you still want to add things to EVA 2.4 or if you focus 100% on EVA3 now. Anyways, here it is. As always, big thanks for the amazing work you do!

[BL-Touch Mount DragonHF.zip](https://github.com/EVA-3D/eva-main/files/8908403/BL-Touch.Mount.DragonHF.zip)

**Comment by pkucmus** [comment]
Thank you, you can file it to contrib. EVA 2 is archived now.
