### ISSUE TITLE
Orbiter + Mosquito = Gap!

### ISSUE THREAD

**Issue by Tylersuard** [EVA-3D/eva-main#90]
Currently the EVA combo for Orbiter and Mosquito introduces a gap where the filament is just hanging in the breeze for about 15 mm.  The Orbiter is specially designed to constrain flexible filament so it has nowhere to go.  Adding a gap below it completely defeats the purpose!

it would be nice if we could get a version with a dorect connection from the orbiter to the mosquito.

**Comment by Yako000** [comment]
You are suppposed to add a piece of bowden tube between the extruder and the hotend. It should tell you how long it needs to be in the list of required hardware.

**Comment by pkucmus** [comment]
Yeah, I think @Yako000 nailed what might be wrong here.
Please see https://main.eva-3d.page/getting_started/#ptfe-lenghts and:
![image](https://user-images.githubusercontent.com/6347418/176963949-603e98bc-19d1-4678-958f-608b1a3d1f44.png)
