### ISSUE TITLE
eva 3.0.1 bltouch mount for mosquito magnum hotend

### ISSUE THREAD

**Issue by daveke0201** [EVA-3D/eva-main#91]
the bl touch mount is to low for the mosquito hotend. retracted probe and nozzle are at the same height
[BL-touch v4.zip](https://github.com/EVA-3D/eva-main/files/8999091/BL-touch.v4.zip)
![WhatsApp Image 2022-06-28 at 10 23 57 AM](https://user-images.githubusercontent.com/108329495/176131448-eeadd0b0-c6a0-45f0-8a6e-49e9f80ae4a9.jpeg)
.

**Comment by pkucmus** [comment]
Please check https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/5887f86caa14d2846bbaf4f9
It should be fixed now

**Comment by daveke0201** [comment]
check

**Comment by pkucmus** [comment]
I made another iteration that moves the BL-Touch mount away from the nozzle (thus allowing shroud space) and a volcano variant. Both can be exported from here: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6e64f1ba8609c44902ccf372/e/e226e1499a99fe1c8452b17d

**Comment by pkucmus** [comment]
Fixed in 3.0.2
